/* ============================================================
 * 타로 덱 데이터 (78장)
 * 해석은 오리지널 서술 (키워드 + 정방향/역방향 한 줄 풀이)
 * ============================================================ */
'use strict';

const TAROT_SUITS = {
  wands:  { name:'완드',    en:'Wands',     glyph:'♣', color:'#f06060', el:'불(火)', theme:'열정과 행동의 기운' },
  cups:   { name:'컵',      en:'Cups',      glyph:'♥', color:'#5aa2ff', el:'물(水)', theme:'감정과 관계의 기운' },
  swords: { name:'소드',    en:'Swords',    glyph:'♠', color:'#c3ccd8', el:'바람(風)', theme:'사고와 진실의 기운' },
  pents:  { name:'펜타클',  en:'Pentacles', glyph:'♦', color:'#e0aa4e', el:'흙(土)', theme:'물질과 현실의 기운' },
};

/* entry: {arc:'major'|'minor', num, name, en, sym, key, up, rev, suit?} */
const TAROT_CARDS = [
/* ---------- 메이저 아르카나 (22장) ---------- */
{arc:'major', num:'0', name:'바보', en:'The Fool', sym:'○', key:'새로운 시작 · 자유 · 가능성',
 up:'순수한 가능성의 카드. 두려움 없이 첫발을 내딛을 때입니다. 계획보다 용기가 먼저입니다.',
 rev:'무모함과 준비 부족을 경고합니다. 뛰어들기 전에 한 번만 더 확인하세요.'},
{arc:'major', num:'I', name:'마법사', en:'The Magician', sym:'✦', key:'창조 · 의지 · 기회',
 up:'가진 것을 총동원하면 만들 수 있습니다. 의지, 기술, 자원이 모두 갖춰진 때입니다.',
 rev:'재능의 오용이나 속임수를 경계하세요. 수단과 목적을 돌아볼 때입니다.'},
{arc:'major', num:'II', name:'여사제', en:'The High Priestess', sym:'☽', key:'직관 · 신비 · 인내',
 up:'내면의 지혜가 답을 알고 있습니다. 조용히 기다리며 직관의 소리에 귀 기울이세요.',
 rev:'감정을 억누르고 표면만 보고 판단하고 있진 않은지 돌아보세요.'},
{arc:'major', num:'III', name:'여황제', en:'The Empress', sym:'♀', key:'풍요 · 돌봄 · 창조',
 up:'베풀고 가꾸면 풍성해집니다. 풍요와 창조, 따뜻한 돌봄의 에너지가 흐릅니다.',
 rev:'과잉보호나 결핍감이 관계를 무겁게 합니다. 채우려 하기보다 비워보세요.'},
{arc:'major', num:'IV', name:'황제', en:'The Emperor', sym:'♂', key:'권위 · 안정 · 통제',
 up:'체계를 세우고 지키면 안정됩니다. 책임감 있는 리더십이 빛을 발하는 때입니다.',
 rev:'경직된 통제나 지배욕이 문제를 키웁니다. 고삐를 조금 늦추세요.'},
{arc:'major', num:'V', name:'교황', en:'The Hierophant', sym:'◈', key:'신념 · 전통 · 조언',
 up:'검증된 길을 따르고 스승이나 조언자를 찾을 때입니다. 전통 속 지혜를 빌리세요.',
 rev:'낡은 관습에 갇혀 있거나 위선적인 권위에 휘둘리고 있습니다.'},
{arc:'major', num:'VI', name:'연인', en:'The Lovers', sym:'♥', key:'사랑 · 선택 · 조화',
 up:'마음이 가는 쪽을 택하되 끝까지 책임지세요. 조화로운 결합의 에너지입니다.',
 rev:'어긋난 관계나 우유부단함이 문제입니다. 선택을 미루면 둘 다 잃습니다.'},
{arc:'major', num:'VII', name:'전차', en:'The Chariot', sym:'➤', key:'승리 · 추진 · 통제',
 up:'의지로 밀어붙이면 돌파합니다. 방향만 분명하다면 승리가 코앞입니다.',
 rev:'방향을 잃고 무리하게 질주하고 있습니다. 멈춰서 나침반을 다시 보세요.'},
{arc:'major', num:'VIII', name:'힘', en:'Strength', sym:'∞', key:'용기 · 인내 · 포용',
 up:'부드러운 강함으로 다스릴 때입니다. 인내와 자비가 거친 것도 길들입니다.',
 rev:'자신감이 흔들리거나 힘을 오남용하고 있습니다. 숨을 고르세요.'},
{arc:'major', num:'IX', name:'은둔자', en:'The Hermit', sym:'✧', key:'성찰 · 지혜 · 고독',
 up:'잠시 물러나 내면을 들여다볼 때입니다. 답은 소음 밖에 있습니다.',
 rev:'고립되어 길을 잃고 있습니다. 혼자 끙끙대지 말고 손을 내미세요.'},
{arc:'major', num:'X', name:'운명의 수레바퀴', en:'Wheel of Fortune', sym:'◎', key:'전환 · 운 · 순환',
 up:'운이 움직이는 전환점입니다. 흐름에 올라타세요. 좋은 변화가 시작됩니다.',
 rev:'예상 밖의 변수나 빗나간 타이밍을 조심하세요. 운의 파도를 읽어야 합니다.'},
{arc:'major', num:'XI', name:'정의', en:'Justice', sym:'⚖', key:'공정 · 책임 · 진실',
 up:'한 만큼 돌아옵니다. 공정하게 처신하면 진실이 당신 편이 됩니다.',
 rev:'불공정한 처사나 책임 회피가 화를 부릅니다. 정직하게 마주하세요.'},
{arc:'major', num:'XII', name:'매달린 사람', en:'The Hanged Man', sym:'▽', key:'희생 · 통찰 · 대기',
 up:'멈춤 속에서 보이는 것이 있습니다. 관점을 뒤집으면 답이 보입니다.',
 rev:'헛된 희생이나 끝없는 미루기입니다. 기다림에도 기한이 필요합니다.'},
{arc:'major', num:'XIII', name:'죽음', en:'Death', sym:'✕', key:'종결 · 변화 · 재생',
 up:'끝은 새로운 시작입니다. 붙잡지 말고 보내주세요. 그 자리에 새싹이 돕니다.',
 rev:'변화를 거부하고 미련에 붙잡혀 있습니다. 놓아야 살 수 있습니다.'},
{arc:'major', num:'XIV', name:'절제', en:'Temperance', sym:'≋', key:'균형 · 중용 · 치유',
 up:'섞고 다듬으면 금상첨화입니다. 균형 잡힌 조율이 치유를 가져옵니다.',
 rev:'과함과 모자람의 불균형이 문제입니다. 중용으로 돌아오세요.'},
{arc:'major', num:'XV', name:'악마', en:'The Devil', sym:'▼', key:'집착 · 유혹 · 속박',
 up:'무엇에 묶여 있는지 직시하세요. 집착의 사슬은 생각보다 헐겁습니다.',
 rev:'속박에서 벗어나는 중입니다. 그림자를 직면한 용기가 자유를 줍니다.'},
{arc:'major', num:'XVI', name:'탑', en:'The Tower', sym:'↯', key:'붕괴 · 각성 · 해방',
 up:'무너질 것은 무너지게 두세요. 붕괴 뒤에 오는 해방이 더 큽니다.',
 rev:'위기가 지연되거나 내면에서 조용히 무너지고 있습니다. 대비하세요.'},
{arc:'major', num:'XVII', name:'별', en:'The Star', sym:'★', key:'희망 · 치유 · 영감',
 up:'어둠 뒤에 오는 빛입니다. 희망을 놓지 마세요. 치유와 영감의 때입니다.',
 rev:'희망을 잃고 방향 감각이 흐려졌습니다. 작은 빛부터 다시 찾으세요.'},
{arc:'major', num:'XVIII', name:'달', en:'The Moon', sym:'☾', key:'불안 · 착각 · 무의식',
 up:'보이는 게 전부가 아닙니다. 불안이 부풀린 그림자를 조심하세요.',
 rev:'불안이 걷히고 진실이 드러납니다. 안개가 걷히는 중입니다.'},
{arc:'major', num:'XIX', name:'태양', en:'The Sun', sym:'☀', key:'성공 · 활력 · 축복',
 up:'만사형통의 빛입니다. 성공과 기쁨, 활력이 가득한 때입니다.',
 rev:'일시적으로 구름이 꼈거나 과신하고 있습니다. 겸손이 빛을 되찾습니다.'},
{arc:'major', num:'XX', name:'심판', en:'Judgement', sym:'◉', key:'각성 · 부활 · 결단',
 up:'과거를 용서하고 다시 일어설 때입니다. 부름에 응답하세요.',
 rev:'자기 의심이 발목을 잡습니다. 과거의 소리에 더 이상 끌려다니지 마세요.'},
{arc:'major', num:'XXI', name:'세계', en:'The World', sym:'⊕', key:'완성 · 성취 · 통합',
 up:'한 사이클의 아름다운 마무리입니다. 완성과 성취를 만끽하세요.',
 rev:'마무리가 한 걸음 모자랍니다. 끝까지 매듭지어야 다음이 열립니다.'},
/* ---------- 마이너 아르카나: 완드 (불·열정과 행동) ---------- */
{arc:'minor', suit:'wands', num:'A', name:'완드 에이스', en:'Ace of Wands', key:'열정의 시작 · 영감',
 up:'불꽃이 붙었습니다. 영감이 올 때 바로 시작하세요.',
 rev:'꺼진 불씨를 살피세요. 때가 아직이거나 에너지가 분산되어 있습니다.'},
{arc:'minor', suit:'wands', num:'2', name:'완드 2', en:'Two of Wands', key:'선택 · 계획 · 과감함',
 up:'두 갈래 길 앞에 섰습니다. 과감히 선택하고 계획을 세우세요.',
 rev:'선택 장애나 계획 차질이 있습니다. 서두르지 말고 정리하세요.'},
{arc:'minor', suit:'wands', num:'3', name:'완드 3', en:'Three of Wands', key:'확장 · 첫 결실 · 전망',
 up:'첫 결실이 보입니다. 시야를 넓히면 더 큰 기회가 옵니다.',
 rev:'지연되거나 기대와 속도가 다릅니다. 조급함을 내려놓으세요.'},
{arc:'minor', suit:'wands', num:'4', name:'완드 4', en:'Four of Wands', key:'안정 · 축하 · 터전',
 up:'안정의 터전이 마련됐습니다. 축하할 일이 생깁니다.',
 rev:'틀에 갇혔거나 축하가 미뤄졌습니다. 틀 밖을 보세요.'},
{arc:'minor', suit:'wands', num:'5', name:'완드 5', en:'Five of Wands', key:'경쟁 · 마찰 · 단련',
 up:'선의의 경쟁입니다. 부딪혀 다듬어지면 더 강해집니다.',
 rev:'소모적인 다툼과 내분이 에너지를 갉아먹습니다.'},
{arc:'minor', suit:'wands', num:'6', name:'완드 6', en:'Six of Wands', key:'승리 · 인정 · 귀환',
 up:'승리자의 귀환입니다. 노력한 만큼 인정받습니다.',
 rev:'인정을 받지 못하거나 자만이 화를 부릅니다. 겸손하세요.'},
{arc:'minor', suit:'wands', num:'7', name:'완드 7', en:'Seven of Wands', key:'방어 · 버팀 · 신념',
 up:'불리해도 버티면 지킵니다. 신념을 굽히지 마세요.',
 rev:'수세에 몰렸습니다. 방어선이 흔들리니 재정비가 필요합니다.'},
{arc:'minor', suit:'wands', num:'8', name:'완드 8', en:'Eight of Wands', key:'속도 · 진전 · 소식',
 up:'일사천리입니다. 속도를 내세요. 좋은 소식이 옵니다.',
 rev:'성급함이 화를 부르거나 소식이 지연됩니다. 브레이크를 확인하세요.'},
{arc:'minor', suit:'wands', num:'9', name:'완드 9', en:'Nine of Wands', key:'인내 · 마지막 힘 · 경계',
 up:'마지막 한 걸음이 남았습니다. 버텨낸 자가 얻습니다.',
 rev:'지쳐서 방어적으로만 변했습니다. 휴식이 먼저입니다.'},
{arc:'minor', suit:'wands', num:'10', name:'완드 10', en:'Ten of Wands', key:'과부하 · 책임 · 내려놓음',
 up:'짊어진 게 너무 무겁습니다. 내려놓을 때를 아는 것도 용기입니다.',
 rev:'과로와 책임 과다가 한계에 달했습니다. 분담하세요.'},
{arc:'minor', suit:'wands', num:'P', name:'완드 시종', en:'Page of Wands', key:'새 소식 · 호기심 · 도전',
 up:'새로운 열정의 소식이 옵니다. 호기심을 따라가 보세요.',
 rev:'산만하거나 헛된 열정에 휩쓸립니다. 한 곳에 집중하세요.'},
{arc:'minor', suit:'wands', num:'N', name:'완드 기사', en:'Knight of Wands', key:'돌진 · 모험 · 추진력',
 up:'거침없이 돌진할 때입니다. 모험이 보상을 줍니다.',
 rev:'무모한 돌진으로 방향을 잃었습니다. 속도보다 방향입니다.'},
{arc:'minor', suit:'wands', num:'Q', name:'완드 여왕', en:'Queen of Wands', key:'매력 · 주도권 · 자신감',
 up:'당당한 매력이 주도권을 쥡니다. 자신감 있게 나서세요.',
 rev:'질투나 자존심 다툼이 생깁니다. 한 걸음 물러나세요.'},
{arc:'minor', suit:'wands', num:'K', name:'완드 왕', en:'King of Wands', key:'비전 · 리더십 · 카리스마',
 up:'비전을 가진 리더의 때입니다. 큰 그림을 그리고 이끄세요.',
 rev:'독단과 허세가 리더십을 갉아먹습니다. 귀를 여세요.'},
/* ---------- 마이너 아르카나: 컵 (물·감정과 관계) ---------- */
{arc:'minor', suit:'cups', num:'A', name:'컵 에이스', en:'Ace of Cups', key:'사랑의 시작 · 열린 마음',
 up:'마음이 열립니다. 사랑과 감정의 새로운 시작입니다.',
 rev:'감정이 과하거나 마음이 닫혀 있습니다. 넘치지도 마르지도 않게.'},
{arc:'minor', suit:'cups', num:'2', name:'컵 2', en:'Two of Cups', key:'교감 · 인연 · 화합',
 up:'마음이 통합니다. 좋은 인연, 조화로운 만남입니다.',
 rev:'마음이 어긋났습니다. 관계의 균형을 다시 맞추세요.'},
{arc:'minor', suit:'cups', num:'3', name:'컵 3', en:'Three of Cups', key:'우정 · 축하 · 나눔',
 up:'함께 나누는 기쁨입니다. 사람들과 어울리세요.',
 rev:'겉도는 어울림에 소외감을 느낍니다. 진심을 나누세요.'},
{arc:'minor', suit:'cups', num:'4', name:'컵 4', en:'Four of Cups', key:'권태 · 성찰 · 재발견',
 up:'권태가 왔습니다. 이미 가진 것을 다시 보세요. 답은 가까이에 있습니다.',
 rev:'권태에서 벗어납니다. 새로운 제안을 받아들이세요.'},
{arc:'minor', suit:'cups', num:'5', name:'컵 5', en:'Five of Cups', key:'상실 · 슬픔 · 남은 것',
 up:'흘린 것에 슬퍼 마세요. 아직 남은 것이 있습니다. 고개를 드세요.',
 rev:'슬픔에서 회복 중입니다. 조금만 더 가면 됩니다.'},
{arc:'minor', suit:'cups', num:'6', name:'컵 6', en:'Six of Cups', key:'추억 · 순수 · 옛 인연',
 up:'추억과 순수함이 힘이 됩니다. 옛 인연이 도움이 됩니다.',
 rev:'과거에 발목 잡혔습니다. 추억에 살지 마세요.'},
{arc:'minor', suit:'cups', num:'7', name:'컵 7', en:'Seven of Cups', key:'환상 · 선택 과다 · 분별',
 up:'선택지가 너무 많습니다. 환상에 속지 말고 본질을 보세요.',
 rev:'환상이 걷힙니다. 선택이 명확해집니다.'},
{arc:'minor', suit:'cups', num:'8', name:'컵 8', en:'Eight of Cups', key:'떠남 · 추구 · 전환',
 up:'더 깊은 의미를 찾아 떠날 때입니다. 미련을 버리세요.',
 rev:'떠나지 못하고 머뭇거립니다. 회피가 답은 아닙니다.'},
{arc:'minor', suit:'cups', num:'9', name:'컵 9', en:'Nine of Cups', key:'소원 성취 · 만족',
 up:'바라던 것이 이루어집니다. 만족을 누리세요.',
 rev:'겉만 번지르르합니다. 탐욕을 경계하세요.'},
{arc:'minor', suit:'cups', num:'10', name:'컵 10', en:'Ten of Cups', key:'완전한 행복 · 화목',
 up:'완전한 행복입니다. 가족과 사랑의 화목이 깃듭니다.',
 rev:'화목이 깨졌습니다. 이상과 현실의 간극을 좁히세요.'},
{arc:'minor', suit:'cups', num:'P', name:'컵 시종', en:'Page of Cups', key:'설렘 · 감수성 · 소식',
 up:'설레는 소식이 옵니다. 감수성이 예민해지는 때입니다.',
 rev:'감정 기복이 심합니다. 유치해지지 않게 조심하세요.'},
{arc:'minor', suit:'cups', num:'N', name:'컵 기사', en:'Knight of Cups', key:'로맨스 · 제안 · 감성',
 up:'로맨틱한 제안이 다가옵니다. 감성을 따라가 보세요.',
 rev:'변덕스럽거나 공허한 약속입니다. 말보다 행동을 보세요.'},
{arc:'minor', suit:'cups', num:'Q', name:'컵 여왕', en:'Queen of Cups', key:'공감 · 치유 · 직관',
 up:'깊은 공감의 치유자입니다. 직관을 믿으세요.',
 rev:'감정에 과몰입해서 상처받기 쉽습니다. 선을 지키세요.'},
{arc:'minor', suit:'cups', num:'K', name:'컵 왕', en:'King of Cups', key:'포용 · 감정의 주인 · 성숙',
 up:'감정의 주인이 되었습니다. 넓은 포용이 빛납니다.',
 rev:'감정을 억누르거나 냉담해졌습니다. 마음을 여세요.'},
/* ---------- 마이너 아르카나: 소드 (바람·사고와 진실) ---------- */
{arc:'minor', suit:'swords', num:'A', name:'소드 에이스', en:'Ace of Swords', key:'진실 · 명쾌한 판단',
 up:'진실의 칼입니다. 명쾌하게 판단하고 자르세요.',
 rev:'오판하거나 말이 상처가 됩니다. 한 박자 쉬고 말하세요.'},
{arc:'minor', suit:'swords', num:'2', name:'소드 2', en:'Two of Swords', key:'균형 · 보류 · 팽팽함',
 up:'팽팽한 균형입니다. 결정을 미루고 정보를 모을 때입니다.',
 rev:'균열이 생겼습니다. 강제된 선택이 다가옵니다.'},
{arc:'minor', suit:'swords', num:'3', name:'소드 3', en:'Three of Swords', key:'아픔 · 진실 · 치유',
 up:'아픈 진실을 인정해야 치유가 시작됩니다. 피하지 마세요.',
 rev:'아픔이 길어지지만 치유도 시작됐습니다. 시간에 맡기세요.'},
{arc:'minor', suit:'swords', num:'4', name:'소드 4', en:'Four of Swords', key:'휴식 · 회복 · 재정비',
 up:'멈춰서 쉬어야 할 때입니다. 휴식이 곧 전략입니다.',
 rev:'번아웃 직전입니다. 강제 휴식이 오기 전에 쉬세요.'},
{arc:'minor', suit:'swords', num:'5', name:'소드 5', en:'Five of Swords', key:'승리의 공허 · 갈등의 대가',
 up:'이겨도 잃는 싸움입니다. 승자의 공허를 헤아리세요.',
 rev:'패배를 인정하고 갈등을 봉합할 때입니다.'},
{arc:'minor', suit:'swords', num:'6', name:'소드 6', en:'Six of Swords', key:'이동 · 회복 · 벗어남',
 up:'고난에서 벗어나는 중입니다. 이동이 답이 됩니다.',
 rev:'미련이 발목을 잡습니다. 정체에서 벗어나세요.'},
{arc:'minor', suit:'swords', num:'7', name:'소드 7', en:'Seven of Swords', key:'독자 해결 · 꾀 · 신중',
 up:'혼자 해결해야 할 일입니다. 꾀가 필요한 때입니다.',
 rev:'숨긴 것이 드러납니다. 혼자 앓지 말고 털어놓으세요.'},
{arc:'minor', suit:'swords', num:'8', name:'소드 8', en:'Eight of Swords', key:'속박 · 자기 제한 · 각성',
 up:'스스로 만든 감옥에 갇혔습니다. 눈을 가린 천을 벗으세요.',
 rev:'속박에서 풀려납니다. 자유가 코앞입니다.'},
{arc:'minor', suit:'swords', num:'9', name:'소드 9', en:'Nine of Swords', key:'불안 · 불면 · 걱정',
 up:'밤잠 설치는 걱정입니다. 대부분은 생각보다 작아집니다.',
 rev:'걱정이 끝납니다. 아침이 오고 있습니다.'},
{arc:'minor', suit:'swords', num:'10', name:'소드 10', en:'Ten of Swords', key:'바닥 · 종결 · 반등',
 up:'바닥을 쳤습니다. 이제 올라갈 일만 남았습니다.',
 rev:'최악은 지났습니다. 회복이 시작됩니다.'},
{arc:'minor', suit:'swords', num:'P', name:'소드 시종', en:'Page of Swords', key:'통찰 · 배움 · 예리함',
 up:'예리한 통찰이 옵니다. 배우고 관찰할 때입니다.',
 rev:'날 선 말이 오해를 부릅니다. 표현을 다듬으세요.'},
{arc:'minor', suit:'swords', num:'N', name:'소드 기사', en:'Knight of Swords', key:'전격 결단 · 돌파',
 up:'전광석화처럼 결단하세요. 돌파의 때입니다.',
 rev:'돌격한 뒤 수습이 필요합니다. 논쟁을 조심하세요.'},
{arc:'minor', suit:'swords', num:'Q', name:'소드 여왕', en:'Queen of Swords', key:'냉철한 지혜 · 독립',
 up:'냉철한 지혜가 빛납니다. 독립적으로 판단하세요.',
 rev:'냉소가 됩니다. 비판보다 해결을 말하세요.'},
{arc:'minor', suit:'swords', num:'K', name:'소드 왕', en:'King of Swords', key:'공정한 판단 · 전문성',
 up:'공정한 판단자입니다. 전문가의 시각을 빌리세요.',
 rev:'냉혹해졌습니다. 권모술수를 경계하세요.'},
/* ---------- 마이너 아르카나: 펜타클 (흙·물질과 현실) ---------- */
{arc:'minor', suit:'pents', num:'A', name:'펜타클 에이스', en:'Ace of Pentacles', key:'현실의 기회 · 씨앗',
 up:'현실적인 씨앗이 떨어졌습니다. 돈과 일의 좋은 기회입니다.',
 rev:'기회를 놓쳤거나 물질에 집착하고 있습니다.'},
{arc:'minor', suit:'pents', num:'2', name:'펜타클 2', en:'Two of Pentacles', key:'균형 잡기 · 유연함',
 up:'여러 일을 저글링 중입니다. 유연하게 균형을 잡으세요.',
 rev:'균형이 무너집니다. 우선순위를 정하세요.'},
{arc:'minor', suit:'pents', num:'3', name:'펜타클 3', en:'Three of Pentacles', key:'실력 인정 · 협업',
 up:'실력을 인정받습니다. 협업의 결실이 맺힙니다.',
 rev:'평가가 박하거나 팀워크에 문제가 있습니다.'},
{arc:'minor', suit:'pents', num:'4', name:'펜타클 4', en:'Four of Pentacles', key:'지킴 · 안정 기반',
 up:'단단히 지키는 것이 답입니다. 안정된 기반 위에 있습니다.',
 rev:'인색해지거나 붙잡고만 있습니다. 쥔 손을 펴세요.'},
{arc:'minor', suit:'pents', num:'5', name:'펜타클 5', en:'Five of Pentacles', key:'어려움 · 도움 청하기',
 up:'물질적으로 힘든 때입니다. 혼자 버티지 말고 도움을 청하세요.',
 rev:'어려움이 끝나갑니다. 도움이 옵니다.'},
{arc:'minor', suit:'pents', num:'6', name:'펜타클 6', en:'Six of Pentacles', key:'나눔 · 선순환 · 베풂',
 up:'베풀고 받는 선순환입니다. 나눔이 돌아옵니다.',
 rev:'불균형한 거래입니다. 빚과 의존을 조심하세요.'},
{arc:'minor', suit:'pents', num:'7', name:'펜타클 7', en:'Seven of Pentacles', key:'기다림 · 장기전 · 평가',
 up:'결실을 기다리는 때입니다. 장기전으로 보세요.',
 rev:'수확이 실망스럽습니다. 방향을 재검토하세요.'},
{arc:'minor', suit:'pents', num:'8', name:'펜타클 8', en:'Eight of Pentacles', key:'장인 정신 · 숙련',
 up:'장인처럼 실력을 쌓으세요. 정성이 실력이 됩니다.',
 rev:'단조로움에 대충 하고 있습니다. 초심을 되찾으세요.'},
{arc:'minor', suit:'pents', num:'9', name:'펜타클 9', en:'Nine of Pentacles', key:'자수성가 · 여유 · 독립',
 up:'일군 자리에 여유가 깃듭니다. 자수성가의 열매입니다.',
 rev:'겉치레에 불과하거나 성공이 외롭습니다.'},
{arc:'minor', suit:'pents', num:'10', name:'펜타클 10', en:'Ten of Pentacles', key:'유산 · 가업 · 대대손손',
 up:'대대손손 이어질 기반입니다. 가업과 유산의 축복입니다.',
 rev:'가족 내 물질 갈등이 있습니다. 돈보다 사람을 보세요.'},
{arc:'minor', suit:'pents', num:'P', name:'펜타클 시종', en:'Page of Pentacles', key:'현실적 배움 · 기회 포착',
 up:'현실적인 배움의 기회입니다. 착실히 시작하세요.',
 rev:'게으름으로 기회를 놓칩니다. 엉덩이를 붙이세요.'},
{arc:'minor', suit:'pents', num:'N', name:'펜타클 기사', en:'Knight of Pentacles', key:'성실 · 꾸준함 · 전진',
 up:'성실하게 한 걸음씩. 꾸준함이 이깁니다.',
 rev:'답답한 고집에 정체됐습니다. 속도를 조절하세요.'},
{arc:'minor', suit:'pents', num:'Q', name:'펜타클 여왕', en:'Queen of Pentacles', key:'알뜰함 · 풍요 · 실속',
 up:'알뜰하게 일군 풍요입니다. 실속 있는 살림의 지혜입니다.',
 rev:'물질 집착이나 과로입니다. 쉼도 자산입니다.'},
{arc:'minor', suit:'pents', num:'K', name:'펜타클 왕', en:'King of Pentacles', key:'성취 · 책임 · 안정',
 up:'이룬 부와 안정의 때입니다. 책임감 있게 지키세요.',
 rev:'탐욕이 눈을 가립니다. 물질만능을 경계하세요.'},
];

if(typeof module !== 'undefined' && module.exports){
  module.exports = { TAROT_CARDS, TAROT_SUITS };
}
